version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: nimda
        MONGO_INITDB_DATABASE: local
    ports:
      - "27017:27017"
      - "28017:28017"